[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe_anchor = "BwAT2NVQuxS4wuvzSd4MjPUbxMZm4yv791C7E62yYJUp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
